### ISSUE TITLE
Embedding media - videos does not set the correct width / height

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-cms#2625]
Any video that gets embedded via the WYSIWYG editor results in the same size video being created:

![image](https://user-images.githubusercontent.com/67215/102271887-d1060e00-3f84-11eb-9483-e3e2dfacc742.png)

I can reproduce this issue in the SilverStripe demo site. Latest version.

it seems to be related to how Utils.php creates an iframe. there is no px set on the end of the width and height which results in the issue

**Comment by kinglozzer** [comment]
This was an issue with an upstream library `embed/embed`, more info here: https://github.com/oscarotero/Embed/issues/417. It should be resolved by a `composer update` (`embed/embed: v3.4.12` contains the fix)

**Comment by LukePercy** [comment]
We've updated to (embed/embed: v3.4.13) but this issue still persists.

**Comment by brynwhyman** [comment]
Hi @LukePercy what version of silverstripe/framework are you running? There's a similar issue that was resolved in 4.6.1+, here: https://github.com/silverstripe/silverstripe-framework/pull/9615

**Comment by LukePercy** [comment]
Hi Bryn, does seem tested as resolved in 4.7. Just be aware simply patching embed/embed alone as suggested doesn't correct this particular issue.
